FROM openjdk:8-jdk-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add curl iproute2

# copy arthas
COPY --from=hengyunabc/arthas:latest /opt/arthas /opt/arthas

WORKDIR /app
COPY /target/sc-B-0.0.1-SNAPSHOT.jar /app
COPY /start.sh /app

EXPOSE 20002
CMD ["/app/start.sh"]